### ISSUE TITLE
Reply Ping Not Recolored

### ISSUE THREAD

**Issue by DracoClaw** [phenom4n4n/blurple-replacer#5]
The ping toggle for replies does not seem to be recolored properly. 

![image](https://user-images.githubusercontent.com/34274162/117870017-3811bf80-b2a4-11eb-8760-4f30a33359cf.png)

as you can see, i have this lavender color that it should be
![image](https://user-images.githubusercontent.com/34274162/117870107-5a0b4200-b2a4-11eb-91b9-d05e960533c5.png)

**Comment by phenom4n4n** [comment]
Since Discord changed it and it is not longer blurple, I will not recolor that.

**Comment by DracoClaw** [comment]
I thought the rebrand made it so nothing is blurple now?
